spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/the-six-universe-dominator
    username: root
    password: root
  freemarker:
    suffix: .html
